package com.tlz.guide

/**
 *
 * Created by Tomlezen.
 * Date: 2017/7/28.
 * Time: 17:40.
 */
object Location {

//    const val TOP_INSIDE = 48
//    const val TOP_OUTSIDE = 49
//    const val BOTTOM_INSIDE = 80
//    const val BOTTOM_OUTSIDE = 81
//    const val CENTER = 17
//    const val CENTER_HORIZONTAL = 1
//    const val CENTER_VERTICAL = 16
//    const val END = 8388613
//    const val START = 8388611


    private val AXIS_SPECIFIED = 0x0001
    private val AXIS_PULL_BEFORE = 0x0002
    private val AXIS_PULL_BEFORE_INSIDE = 0x0008
    private val AXIS_PULL_AFTER = 0x0004
    private val AXIS_PULL_AFTER_INSIDE = 0x00016
    private val AXIS_X_SHIFT = 0
    private val AXIS_Y_SHIFT = 4
    val TOP = AXIS_PULL_BEFORE or AXIS_SPECIFIED shl AXIS_Y_SHIFT
    val TOP_INSIDE = AXIS_PULL_BEFORE_INSIDE or AXIS_SPECIFIED shl AXIS_Y_SHIFT
    val BOTTOM = AXIS_PULL_AFTER or AXIS_SPECIFIED shl AXIS_Y_SHIFT
    val BOTTOM_INSIDE = AXIS_PULL_AFTER_INSIDE or AXIS_SPECIFIED shl AXIS_Y_SHIFT
    private val LEFT = AXIS_PULL_BEFORE or AXIS_SPECIFIED shl AXIS_X_SHIFT
    private val LEFT_INSIDE = AXIS_PULL_BEFORE_INSIDE or AXIS_SPECIFIED shl AXIS_X_SHIFT
    private val RIGHT = AXIS_PULL_AFTER or AXIS_SPECIFIED shl AXIS_X_SHIFT
    private val RIGHT_INSIDE = AXIS_PULL_AFTER_INSIDE or AXIS_SPECIFIED shl AXIS_X_SHIFT
    val CENTER_VERTICAL = AXIS_SPECIFIED shl AXIS_Y_SHIFT + 12121
    val CENTER_HORIZONTAL = AXIS_SPECIFIED shl AXIS_X_SHIFT + 1313
    val CENTER = CENTER_VERTICAL or CENTER_HORIZONTAL
    private val RELATIVE_LAYOUT_DIRECTION = 0x00800000
    val START = RELATIVE_LAYOUT_DIRECTION or LEFT
    val START_INSIDE = RELATIVE_LAYOUT_DIRECTION or LEFT_INSIDE
    val END = RELATIVE_LAYOUT_DIRECTION or RIGHT
    val END_INSIDE = RELATIVE_LAYOUT_DIRECTION or RIGHT_INSIDE

}